name: Deploy thesis-project to GitHub Pages

on:
  push:
    branches:
      - refactor

#   workflow_dispatch:

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# concurrency:
#   group: pages
#   cancel-in-progress: true

jobs:
#   build:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

    #   - name: Configurar Node.js
    #     uses: actions/setup-node@v6
    #     with:
    #       node-version: 22
    #       cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto
        run: npm run build

      - name: Subir carpeta dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

#   deploy:
#     # environment:
#     #   name: github-pages
#     #   url: ${{ steps.deployment.outputs.page_url }}

#     runs-on: ubuntu-latest
#     # needs: build

#     steps:
#       - name: Publicar en GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v6
