# name: Deploy thesis-project to GitHub Pages

# on:
#   push:
#     branches:
#       - refactor

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Descargar repositorio
#         uses: actions/checkout@v6

#       - name: Instalar dependencias
#         run: npm install

#       - name: Construir proyecto
#         run: npm run build

#       - name: Subir carpeta dist
#         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
#         with:
#           name: dist
#           path: ./dist/
